# Generated by Django 2.0.1 on 2018-01-21 01:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ifoundadog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dog_sex_choices',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_id',
            field=models.CharField(default='XXXXXXX', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner_address',
            field=models.CharField(default='Address', max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='XXX-XXX-XXXX', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dog_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
