# Generated by Django 2.0.3 on 2018-03-25 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_ifoundadog', '0002_auto_20180325_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDogProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=32)),
                ('is_lost', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='First Name', max_length=64)),
                ('last_name', models.CharField(default='Last Name', max_length=64)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d')),
                ('phone_number', models.CharField(default='XXXXXXXXXX', max_length=12)),
                ('license_id', models.CharField(default='XXXXXXX', max_length=7)),
                ('owner_address', models.CharField(default='Address', max_length=256)),
                ('payment_date', models.DateTimeField(default=datetime.datetime.now)),
                ('years_issued', models.IntegerField(default=1)),
                ('dog_sex_choices', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('neutered', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
