# Generated by Django 2.0.2 on 2018-03-25 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ifoundadog', '0003_auto_20180325_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdogprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
