# Generated by Django 2.0.1 on 2018-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ifoundadog', '0003_auto_20180122_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='XXXXXXXXXX', max_length=12),
        ),
    ]
