# Generated by Django 2.0.2 on 2018-03-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ifoundadog', '0004_auto_20180224_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_Lost',
            field=models.BooleanField(default=False),
        ),
    ]
